# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    always_authenticate_before_granting:    true 
    erase_credentials:                      false 
    session_fixation_strategy:              none 

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        chain_provider:
            chain: 
                providers: [ auth_secured ]
        auth_secured:
            #id: aria.security.user.provider.api
            id: auth_user_provider
            
    firewalls:
        debug:
            pattern:    ^/(_(profiler|wdt)|css|images|js)/
            security:   false
        password:
            pattern:    ^/Users/reset
            security:   false
        auth_secured:
            pattern:   ^/user/login/
            stateless: true
            auth:      true