# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    auth.security.authentication.provider:
        class: AppBundle\Security\Authentication\Provider\AuthProvider
        arguments: [ dummy_arg ]
        
    auth_user_provider:
        class: AppBundle\Security\User\AuthUser
        arguments:
            - @service_container                    

    auth.security.authentication.listener:
        class: AppBundle\Security\Firewall\AuthListener
        arguments:
            - @security.context
            - @security.authentication.manager
            - @service_container            