AppBundle\Document\User:
    getters:
        email:
            - NotBlank:
                message: Email address cannot be blank
            - Email:
                message: Email address is invalid
        mobile:
            - Length: 
                max: 10
                maxMessage: Mobile number should be 10 characters
        confirmPassword:
            - NotBlank:
                message: Confirm Password cannot be blank
        password:
            - NotBlank:
                message: Password cannot be blank                
        name:
            - NotBlank:
                message: Name cannot be blank
            - Length:
                max: 100
                maxMessage: Name should not exceed 100 characters
        confirmPasswordMatched:
            - 'True':
                message: Password and confirm password aren't matching                     
            